### get all
GET   http://localhost:3003/api/blogs/
Content-Type: application/json

### post
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXhzcCIsImlkIjoiNjk5ZDczZGJlZjVkYjRiYzFhMWNlMDAwIiwiaWF0IjoxNzcxOTMwMzU1fQ.65X6G_PQ1g7Qelw6Vh2CmLN2w1q_OnQgvH68BbMhjmg

{
    "title": "new blog by alex3",
  "author": "alex",
  "url": "url",
  "likes": 0
}

### get all users
GET   http://localhost:3003/api/users/
Content-Type: application/json


### create a new user
post   http://localhost:3003/api/users/
Content-Type: application/json

{
  "username": "alexsp",
  "name": "Alexey",
  "password": "testtest"
}

### delete a blog
delete http://localhost:3003/api/blogs/699da3f7a48def156a4d1d5c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXhzcCIsImlkIjoiNjk5ZDczZGJlZjVkYjRiYzFhMWNlMDAwIiwiaWF0IjoxNzcxOTQ2MTg4fQ.Yl-E9VuwqBGRgZCn6uK1oKukjVLJx3zJJzliYYd0Kz