### get all
GET   http://localhost:3003/api/blogs/
Content-Type: application/json

### post
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "new blog 1",
  "author": "Avrely",
  "url": "some url 4",
  "likes": 15
}

### get all users
GET   http://localhost:3003/api/users/
Content-Type: application/json


### create a new user
post   http://localhost:3003/api/users/
Content-Type: application/json

{
  "username": "alexsp",
  "name": "Alexey",
  "password": "testtest"
}